### ISSUE TITLE
Doesn't work. I can see only white screen

### ISSUE THREAD

**Issue by alien2003** [XNBlank/discord-linux#16] opened 2016-01-18 16:28 UTC
[23086:0118/182736:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[23119:0118/182737:INFO:renderer_main.cc(200)] Renderer process started
[23123:0118/182737:INFO:renderer_main.cc(200)] Renderer process started
[23086:0118/182738:ERROR:browser_main_loop.cc(237)] GLib-GObject: gsignal.c:2516: signal 'child-added' is invalid for instance '0x24b9c98d08b0' of type 'GtkMenu'
[23086:0118/182738:INFO:CONSOLE(25)] "Loading up the webframe.", source: file:///opt/discord/resources/app/index.html (25)
[23140:0118/182738:INFO:renderer_main.cc(200)] Renderer process started

Installed from AUR, x64
Other electron apps work perfectly

**Comment by XNBlank** [comment] 2016-01-18 18:21
Hi. Please see https://github.com/XNBlank/discord-linux/issues/14#issuecomment-164341250

Sorry for the inconvenience.

**Comment by alien2003** [comment] 2016-01-18 19:28
Still no luck with it :(

**Comment by jacobmischka** [comment] 2016-01-19 04:17
You could be having the same problem someone else was having. I think the only solution is to use a newer version of electron. I'll submit a pull request tonight to update it.

**Comment by alien2003** [comment] 2016-01-19 13:51
thanks

**Comment by jacobmischka** [comment] 2016-01-20 02:26
If the problem is what I thought it was, should be fixed with #18.

**Comment by XNBlank** [comment] 2016-01-24 00:05
Should be fixed.

**Closed as completed by XNBlank** 2016-01-24 00:05 UTC

**Comment by alien2003** [comment] 2016-01-24 12:16
Fixer, thx!
